// mapData.js

// State color groupings
window.data1 = [
  ['IN-UP'],
  ['IN-BR', 'IN-MH'],
  ['IN-WB', 'IN-MP', 'IN-RJ', 'IN-TN', 'IN-GJ', 'IN-KA', 'IN-AP'],
  ['IN-OR', 'IN-JH', 'IN-TG', 'IN-KL', 'IN-AS', 'IN-PB', 'IN-HR', 'IN-CT', 'IN-UT', 'IN-DL', 'IN-JK'],
  ['IN-HP', 'IN-TR', 'IN-ML', 'IN-MN', 'IN-NL', 'IN-PY', 'IN-GA', 'IN-AR', 'IN-DN', 'IN-MZ', 'IN-CH']
];

// State IDs
window.ids = [
  'IN-AN', 'IN-AP', 'IN-AR', 'IN-AS', 'IN-BR', 'IN-CH', 'IN-CT', 'IN-DD', 'IN-DL', 'IN-DN', 'IN-GA', 'IN-GJ', 
  'IN-HP', 'IN-HR', 'IN-JH', 'IN-JK', 'IN-KA', 'IN-KL', 'IN-LD', 'IN-MH', 'IN-ML', 'IN-MN', 'IN-MP',
  'IN-MZ', 'IN-NL', 'IN-OR', 'IN-PB', 'IN-PY', 'IN-RJ', 'IN-SK', 'IN-TG', 'IN-TN', 'IN-TR',
  'IN-UP', 'IN-UT', 'IN-WB'
];

// State details
window.stateDetails = {
  "Andaman and Nicobar Islands": {
    dance: "Nicobari dance",
    music: "Tribal folk songs",
    handicrafts: "Shell crafts, wood carving",
    painting: "Tribal motifs",
    textiles: "Coconut fiber weaving",
    stone_art: "Coral stone carving",
    metal_art: "Traditional jewelry",
    sculpture: "Wooden tribal sculptures",
    oral_storytelling: "Tribal legends",
    rituals: "Tribal harvest rituals"
  },
  "Andhra Pradesh": {
    dance: "Kuchipudi",
    music: "Carnatic music",
    handicrafts: "Kalamkari, Kondapalli toys",
    painting: "Kalamkari art",
    textiles: "Uppada, Venkatagiri sarees",
    stone_art: "Lepakshi stone carvings",
    metal_art: "Etikoppaka lacquerware",
    sculpture: "Amaravati Buddhist sculptures",
    oral_storytelling: "Burra Katha",
    rituals: "Ugadi, Sankranti"
  },
  "Arunachal Pradesh": {
    dance: "Ponung, Aji Lamu",
    music: "Tribal folk music",
    handicrafts: "Bamboo and cane crafts",
    painting: "Thangka painting",
    textiles: "Monpa carpets, Adi shawls",
    stone_art: "Monastery stonework",
    metal_art: "Tribal jewelry",
    sculpture: "Wooden masks",
    oral_storytelling: "Tribal myths",
    rituals: "Solung, Losar"
  },
  "Assam": {
    dance: "Bihu, Sattriya",
    music: "Borgeet, folk songs",
    handicrafts: "Assam silk, bamboo crafts",
    painting: "Assamese motifs",
    textiles: "Muga, Eri silk",
    stone_art: "Kamakhya temple carvings",
    metal_art: "Bell metal craft (Sarthebari)",
    sculpture: "Terracotta figurines",
    oral_storytelling: "Ojapali, Xattriya",
    rituals: "Bihu festival"
  },
  "Bihar": {
    dance: "Jat-Jatin, Chhau",
    music: "Folk songs, Bhojpuri music",
    handicrafts: "Madhubani painting",
    painting: "Madhubani art",
    textiles: "Bhagalpuri silk",
    stone_art: "Bodh Gaya carvings",
    metal_art: "Brassware",
    sculpture: "Stone Buddha statues",
    oral_storytelling: "Birha, Sohar",
    rituals: "Chhath Puja"
  },
  "Chandigarh": {
    dance: "Giddha, Bhangra",
    music: "Punjabi folk",
    handicrafts: "Phulkari embroidery",
    painting: "Modern art",
    textiles: "Phulkari textiles",
    stone_art: "Rock Garden installations",
    metal_art: "Decorative metalwork",
    sculpture: "Modern sculptures",
    oral_storytelling: "Punjabi folk tales",
    rituals: "Lohri, Teej"
  },
  "Chhattisgarh": {
    dance: "Panthi, Raut Nacha",
    music: "Pandavani",
    handicrafts: "bamboo work",
    painting: "Tribal wall painting",
    textiles: "Kosa silk",
    stone_art: "Tribal stone carving",
    metal_art: "Dhokra art",
    sculpture: "Tribal wooden sculptures",
    oral_storytelling: "Pandavani",
    rituals: "Hareli, Pola"
  },
  "Dadra and Nagar Haveli": {
    dance: "Tari, Dhol dance",
    music: "Tribal folk",
    handicrafts: "Warli painting",
    painting: "Warli art",
    textiles: "Tribal weaving",
    stone_art: "Local stonework",
    metal_art: "Traditional jewelry",
    sculpture: "Wooden masks",
    oral_storytelling: "Tribal storytelling",
    rituals: "Tarpa dance rituals"
  },
  "Daman and Diu": {
    dance: "Portuguese folk dance",
    music: "Mando music",
    handicrafts: "Shell crafts",
    painting: "Local motifs",
    textiles: "Embroidered textiles",
    stone_art: "Church stonework",
    metal_art: "Silver jewelry",
    sculpture: "Christian statues",
    oral_storytelling: "Portuguese legends",
    rituals: "Feast of St. Francis Xavier"
  },
  "Delhi": {
    dance: "Kathak",
    music: "Qawwali, classical music",
    handicrafts: "Zardozi embroidery",
    painting: "Miniature art",
    textiles: "Zardozi, Jamdani",
    stone_art: "Red Fort, Qutub Minar carvings",
    metal_art: "Meenakari jewelry",
    sculpture: "Mughal garden sculptures",
    oral_storytelling: "Dastangoi",
    rituals: "Ram Lila, Urs"
  },
  "Goa": {
    dance: "Fugdi, Dhalo",
    music: "Mando, Dulpod",
    handicrafts: "Kunbi sarees, coconut crafts",
    painting: "Christian art",
    textiles: "Kunbi sarees",
    stone_art: "Church stonework",
    metal_art: "Brassware",
    sculpture: "Azulejos tiles",
    oral_storytelling: "Mando songs",
    rituals: "Carnival, Shigmo"
  },
  "Gujarat": {
    dance: "Garba, Dandiya Raas",
    music: "Sugam Sangeet, Bhajan",
    handicrafts: "Bandhani, Patola silk",
    painting: "Rogan art, Pithora painting",
    textiles: "Patola, Bandhani",
    stone_art: "Somnath temple carvings",
    metal_art: "Brass and copper utensils",
    sculpture: "Stone and wood sculptures",
    oral_storytelling: "Dayro, Bhavai",
    rituals: "Navratri, Uttarayan"
  },
  "Haryana": {
    dance: "Phag, Dhamal",
    music: "Ragini, folk songs",
    handicrafts: "Phulkari embroidery",
    painting: "Folk motifs",
    textiles: "Phulkari textiles",
    stone_art: "Temple stonework",
    metal_art: "Brassware",
    sculpture: "Terracotta figurines",
    oral_storytelling: "Haryanvi folk tales",
    rituals: "Gugga Naumi"
  },
  "Himachal Pradesh": {
    dance: "Nati, Kullu",
    music: "Folk songs",
    handicrafts: "Kullu shawls, wood carving",
    painting: "Miniature painting",
    textiles: "Kullu shawls",
    stone_art: "Temple carvings",
    metal_art: "Chamba Rumal embroidery",
    sculpture: "Wooden temple sculptures",
    oral_storytelling: "Folk ballads",
    rituals: "Kullu Dussehra"
  },
  "Jharkhand": {
    dance: "Jhumar, Paika",
    music: "Tribal music",
    handicrafts: "Dokra craft, bamboo work",
    painting: "Sohrai, Kohbar painting",
    textiles: "Tribal weaving",
    stone_art: "Stone carvings",
    metal_art: "Dokra art",
    sculpture: "Wooden tribal sculptures",
    oral_storytelling: "Folk tales",
    rituals: "Sarhul, Karma"
  },
  "Jammu and Kashmir": {
    dance: "Rouf, Dumhal",
    music: "Sufiana Kalam",
    handicrafts: "Pashmina shawls",
    painting: "Kashmiri motifs",
    textiles: "Pashmina, Kani shawls",
    stone_art: "Temple and mosque carvings",
    metal_art: "Copperware",
    sculpture: "Wood carving",
    oral_storytelling: "Kashmiri folk tales",
    rituals: "Shivratri, Eid"
  },
  "Karnataka": {
    dance: "Yakshagana, Dollu Kunitha",
    music: "Carnatic music",
    handicrafts: "Mysore silk",
    painting: "Mysore painting",
    textiles: "Ilkal, Mysore silk",
    stone_art: "Hampi stone carvings",
    metal_art: "Bidriware",
    sculpture: "Bronze & stone sculptures",
    oral_storytelling: "Harikathe",
    rituals: "Dasara, Karaga"
  },
  "Kerala": {
    dance: "Kathakali, Mohiniyattam",
    music: "Sopana Sangeetham",
    handicrafts: "Coir products, mural art",
    painting: "Kerala mural painting",
    textiles: "Kasavu sarees",
    stone_art: "Temple stonework",
    metal_art: "Aranmula mirrors",
    sculpture: "Wooden temple sculptures",
    oral_storytelling: "Vadakkan Pattukal",
    rituals: "Theyyam, Onam"
  },
  "Lakshadweep": {
    dance: "Lava dance",
    music: "Folk songs",
    handicrafts: "Coconut crafts",
    painting: "Island motifs",
    textiles: "Coconut fiber weaving",
    stone_art: "Coral stone carving",
    metal_art: "Traditional jewelry",
    sculpture: "Wooden tribal sculptures",
    oral_storytelling: "Island legends",
    rituals: "Eid, harvest rituals"
  },
  "Madhya Pradesh": {
    dance: "Matki, Rai",
    music: "Folk Songs",
    handicrafts: "Chanderi Sarees, Zari Work",
    painting: "Gond, Pithora Painting",
    textiles: "Chanderi, Maheshwari Sarees",
    stone_art: "Khajuraho Temple Carvings",
    metal_art: "Bell Metal Craft",
    sculpture: "Stone and Bronze Sculptures",
    oral_storytelling: "Folk Legends, Pandavani",
    rituals: "Bhagoria Festival"
  },        
  "Maharashtra": {
    dance: "Lavani, Tamasha",
    music: "Natya Sangeet, Bhavageet",
    handicrafts: "Paithani sarees, Warli art",
    painting: "Warli art",
    textiles: "Paithani, Himroo",
    stone_art: "Ajanta, Ellora carvings",
    metal_art: "Sawantwadi lacquerware",
    sculpture: "Stone and bronze sculptures",
    oral_storytelling: "Powada, Gondhal",
    rituals: "Ganesh Chaturthi"
  },
  "Manipur": {
    dance: "Manipuri, Lai Haraoba",
    music: "Folk music",
    handicrafts: "Cane and bamboo crafts",
    painting: "Tribal motifs",
    textiles: "Shaphee Lanphee textile",
    stone_art: "Temple stonework",
    metal_art: "Tribal jewelry",
    sculpture: "Wooden masks",
    oral_storytelling: "Folk tales",
    rituals: "Lai Haraoba"
  },
  "Meghalaya": {
    dance: "Wangala, Shad Suk Mynsiem",
    music: "Tribal folk",
    handicrafts: "Bamboo crafts, cane mats",
    painting: "Tribal motifs",
    textiles: "Tribal weaving",
    stone_art: "Sacred groves stonework",
    metal_art: "Traditional jewelry",
    sculpture: "Wooden masks",
    oral_storytelling: "Folk legends",
    rituals: "Wangala festival"
  },
  "Mizoram": {
    dance: "Cheraw (Bamboo dance)",
    music: "Folk songs",
    handicrafts: "Bamboo and cane crafts",
    painting: "Tribal motifs",
    textiles: "Puan textile",
    stone_art: "Stone monoliths",
    metal_art: "Traditional jewelry",
    sculpture: "Wooden carvings",
    oral_storytelling: "Folk tales",
    rituals: "Chapchar Kut"
  },
  "Nagaland": {
    dance: "Chang Lo, Zeliang",
    music: "Folk music",
    handicrafts: "Naga shawls, wood carving",
    painting: "Tribal motifs",
    textiles: "Naga shawls",
    stone_art: "Tribal stonework",
    metal_art: "Brass and bead jewelry",
    sculpture: "Wooden carvings",
    oral_storytelling: "Folktales, legends",
    rituals: "Hornbill festival"
  },
  "Odisha": {
    dance: "Odissi, Gotipua",
    music: "Odissi music",
    handicrafts: "Pattachitra, filigree",
    painting: "Pattachitra painting",
    textiles: "Sambalpuri, Bomkai sarees",
    stone_art: "Konark temple carvings",
    metal_art: "Dokra, silver filigree",
    sculpture: "Stone temple sculptures",
    oral_storytelling: "Pala, Daskathia",
    rituals: "Rath Yatra"
  },
  "Puducherry": {
    dance: "Bharatanatyam, French folk",
    music: "Carnatic music",
    handicrafts: "Pottery, textiles",
    painting: "French-Tamil fusion art",
    textiles: "Handloom sarees",
    stone_art: "Church stonework",
    metal_art: "Brassware",
    sculpture: "Terracotta figurines",
    oral_storytelling: "Folk tales",
    rituals: "Masi Magam"
  },
  "Punjab": {
    dance: "Bhangra, Giddha",
    music: "Punjabi folk, Sufi music",
    handicrafts: "Phulkari embroidery",
    painting: "Folk motifs",
    textiles: "Phulkari textiles",
    stone_art: "Golden Temple carvings",
    metal_art: "Punjabi jutti, brassware",
    sculpture: "Sikh religious statues",
    oral_storytelling: "Heer Ranjha",
    rituals: "Lohri, Baisakhi"
  },
  "Rajasthan": {
    dance: "Ghoomar, Kalbelia",
    music: "Maand, folk songs",
    handicrafts: "Blue pottery, Bandhani",
    painting: "Miniature painting",
    textiles: "Bandhani, Leheriya",
    stone_art: "Fort and temple carvings",
    metal_art: "Brassware, Meenakari",
    sculpture: "Kathputli (puppetry)",
    oral_storytelling: "Phad, Pabuji ki Phad",
    rituals: "Gangaur, Teej"
  },
  "Sikkim": {
    dance: "Chutkay, Singhi Chaam",
    music: "Folk music",
    handicrafts: "Thangka painting",
    painting: "Thangka art",
    textiles: "Lepcha weaving",
    stone_art: "Monastery stonework",
    metal_art: "Traditional jewelry",
    sculpture: "Buddhist statues",
    oral_storytelling: "Folk tales",
    rituals: "Losar, Pang Lhabsol"
  },
  "Tamil Nadu": {
    dance: "Bharatanatyam, Karagattam",
    music: "Carnatic music",
    handicrafts: "Tanjore art, bronze sculpture",
    painting: "Tanjore painting",
    textiles: "Kanchipuram silk",
    stone_art: "Mahabalipuram carvings",
    metal_art: "Bronze idols",
    sculpture: "Temple sculptures",
    oral_storytelling: "Villupattu",
    rituals: "Pongal, Aadi Perukku"
  },
  "Telangana": {
    dance: "Perini, Lambadi",
    music: "Folk songs",
    handicrafts: "Nirmal & Cheriyal paintings",
    painting: "Cheriyal scroll painting",
    textiles: "Pochampally Ikat",
    stone_art: "Ramappa temple carvings",
    metal_art: "Bidriware",
    sculpture: "Temple sculptures",
    oral_storytelling: "Burra Katha",
    rituals: "Bonalu, Bathukamma"
  },
  "Tripura": {
    dance: "Hojagiri, Garia",
    music: "Tribal folk",
    handicrafts: "Bamboo and cane crafts",
    painting: "Tribal motifs",
    textiles: "Handloom textiles",
    stone_art: "Unakoti carvings",
    metal_art: "Brassware",
    sculpture: "Stone and wood carvings",
    oral_storytelling: "Folk tales",
    rituals: "Garia Puja"
  },
  "Uttar Pradesh": {
    dance: "Kathak, Raslila",
    music: "Hindustani classical, folk songs",
    handicrafts: "Chikankari, brassware",
    painting: "Miniature painting",
    textiles: "Banarasi silk",
    stone_art: "Varanasi temple carvings",
    metal_art: "Brassware (Moradabad)",
    sculpture: "Terracotta figurines",
    oral_storytelling: "Birha, Nautanki",
    rituals: "Kumbh Mela, Ram Lila"
  },
  "Uttarakhand": {
    dance: "Chholiya, Jhora",
    music: "Garhwali, Kumaoni folk",
    handicrafts: "Aipan art, woolen crafts",
    painting: "Aipan painting",
    textiles: "Ringaal bamboo craft",
    stone_art: "Temple carvings",
    metal_art: "Copperware",
    sculpture: "Wooden temple sculptures",
    oral_storytelling: "Folk ballads",
    rituals: "Nanda Devi Raj Jat"
  },
  "West Bengal": {
    dance: "Gaudiya Nritya, Chhau",
    music: "Rabindra Sangeet, Baul",
    handicrafts: "Terracotta, Shola crafts",
    painting: "Patachitra painting",
    textiles: "Baluchari, Kantha embroidery",
    stone_art: "Temple carvings",
    metal_art: "Dokra art",
    sculpture: "Clay Durga idols",
    oral_storytelling: "Jatra, Kavigan",
    rituals: "Durga Puja, Poush Mela"
  }
};